project/myVacation/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileAllowed, FileRequired
from flask_uploads import UploadSet, IMAGES
from wtforms import StringField, TextAreaField
from wtforms.validators import DataRequired, Length
from wtforms.fields.html5 import DateField

images = UploadSet('images', IMAGES)


class LogVacationForm(FlaskForm):
    vacation_name = StringField('Vacation Name', validators=[DataRequired(), Length(min=6, max=25)])
    location = StringField('Location', validators=[DataRequired()])
    with_who = StringField('With_Who')
    description = TextAreaField('Description', render_kw={
        'class': 'vacation_description',
        'rows': 10
    })
    photo = FileField('Select Images', validators=[
        # FileRequired(),
        FileAllowed(['jpg', 'png'], 'Images only')],
                      render_kw={'multiple': True,}
                      )
    when = DateField('when', validators=[DataRequired()])


class EditVacationFrom(FlaskForm):
    photo = FileField('Select Images', validators=[
        # FileRequired(),
        FileAllowed(['jpg', 'png'], 'Images only')],
                      render_kw={'multiple': True,}
                      )
    description = TextAreaField('Description', render_kw={
        'class': 'vacation_description',
        'rows': 10
    })
    location = StringField('Location', validators=[DataRequired()])
    with_who = StringField('With_Who')

project/comments/views.py
from flask import flash, redirect, render_template, request, session, url_for, Blueprint
from datetime import datetime
from project.models import Comments
from project import db

from project.funcs.general_funcs import redirect_dest

comments_blueprint = Blueprint('comments', __name__)


@comments_blueprint.route('/post_comment/<int:vacation_id>', methods=['POST'])
def log_comment(vacation_id):
    try:
        new_comment = Comments(
            user_name=session['name'],
            text=request.form['comment'],
            date=datetime.now(),
            vacation_id=vacation_id,
        )

        db.session.add(new_comment)
        db.session.commit()
    except KeyError:
        flash('You must log-in to leave a comment')
        return redirect(url_for('user.login'))
    return redirect_dest(fallback=url_for('myVacation.main'))

project/myVacation/views.py
import os
import json
from datetime import datetime
from datetime import date
from functools import wraps

from flask import flash, redirect, render_template, request, session, url_for, Blueprint, abort
from slugify import slugify

from project import db, app
from project.models import Vacation, User, VacationPhoto, Comments
from project.myVacation.forms import LogVacationForm, EditVacationFrom

from project.funcs.general_funcs import _hash_image_name, upload_to_s3, delete_from_s3
from project.funcs.image_manipulation import resize_img

import traceback

myVacation_blueprint = Blueprint('myVacation', __name__)


def login_required(test):
    @wraps(test)
    def wrap(*args, **kwargs):
        if 'logged_in' in session:
            return test(*args, **kwargs)
        else:
            flash('You need to log in !!')
            return redirect(url_for('users.login'))

    return wrap


def _user_img_folder(form, file_name):
    username = session['name']
    try:
        vacation_name = slugify(form.vacation_name.data)
    except:
        vacation_name = form
    directory = os.path.join(username, vacation_name)
    directory = os.path.join(app.config['IMG_UPLOAD_FOLDER'], directory)
    return directory + '/' + file_name


def _get_date(form):
    year, month, day = request.form.get('when').split('-')
    vac_date = date(int(year), int(month), int(day))
    return vac_date


def _get_privacy_bool(form):
    privacy = False
    if request.form.get('public'):
        privacy = True
    return privacy


def _is_image():
    if request.files['photo'].filename != '':
        return True
    return False


def _save_vacation(form):
    vacation = Vacation(slugify(form.vacation_name.data),
                        form.location.data,
                        form.with_who.data,
                        form.description.data,
                        session['user_id'],
                        _get_privacy_bool(form),
                        datetime.utcnow(),
                        _get_date(form)
                        )
    db.session.add(vacation)
    db.session.commit()


def _save_photos(form, normalized_image_names):
    try:
        vac = db.session.query(Vacation).filter(Vacation.name == slugify(form.vacation_name.data)).one()
    except:
        vac = db.session.query(Vacation).filter(Vacation.name == form).one()
    print('Adding image names to the DB')
    for image_name in normalized_image_names:
        image = VacationPhoto(
            image_name,
            vac.id
        )
        db.session.add(image)
        db.session.commit()


@myVacation_blueprint.route('/myVacation', methods=['GET'])
@login_required
def main():
    return render_template('myVacation.html')


@myVacation_blueprint.route('/myVacation/<string:vacation_name>', methods=['GET'])
# @login_required
def vacation(vacation_name=None):
    photo_names = []
    all_comments = []
    logged = False
    owner = False
    session['dest'] = '/edit?next=/myVacation/' + vacation_name
    try:
        vacation_info = Vacation.query.filter_by(name=vacation_name).first()

        if 'logged_in' in session:
            logged = True
            if vacation_info.user_id == User.query.filter_by(name=session['name']).first().id:
                owner = True

        if vacation_info is None:
            abort(404)

        vacation_comments = Comments.query.filter_by(vacation_id=vacation_info.id).all()

        for comment in vacation_comments:
            all_comments.append([comment.user_name,
                                 comment.text,
                                 comment.date]
                                )

        image_data = VacationPhoto.query.filter_by(vacation_id=vacation_info.id).all()
        user_data = User.query.filter_by(id=vacation_info.user_id).first()

        for i in image_data:
            file = '/'.join([app.config['AWS_IMG_SRC'], user_data.name, vacation_info.name, i.photo_name])
            photo_names.append(file)
    except Exception as e:
        traceback.print_exc()
        abort(404)

    return render_template('vacation.html',
                           vacation=vacation_info,
                           photo_names=photo_names,
                           logged=logged,
                           comments=all_comments,
                           owner=owner
                           )


def _img_preparation(img_size, image, form):
    processed_image_name = _hash_image_name(image, img_size)
    large_image = resize_img(image, img_size)
    directory = _user_img_folder(form, processed_image_name)
    return processed_image_name, large_image, directory


@myVacation_blueprint.route('/myVacation/logVacation', methods=['GET', 'POST'])
@login_required
def log_vacation(vacation_name=None):
    error = None
    form = LogVacationForm()

    if request.method == 'POST':
        if form.validate_on_submit():
            try:
                normalized_image_names = []
                if _is_image():
                    uploaded_images = request.files.getlist('photo')
                    for image in uploaded_images:
                        image_size = 'large'
                        processed_image_name, large_image, directory = _img_preparation(image_size, image, form)
                        upload_to_s3(str(directory), large_image, app.config['IMAGES_BUCKET_NAME'])
                        normalized_image_names.append(processed_image_name)

                _save_vacation(form)
                if _is_image():
                    _save_photos(form, normalized_image_names)

                flash('Vacation saved')
                return redirect(url_for('myVacation.log_vacation'))
            except Exception as e:
                traceback.print_exc()
        return redirect(url_for('myVacation.log_vacation'))
    return render_template('logVacation.html', form=form, error=error)


@myVacation_blueprint.route('/edit', methods=['GET', 'POST'])
@login_required
def edit():
    form = EditVacationFrom()
    Qparam = request.args.get('next')
    target = Qparam.split('/')[2]

    vacation_info = Vacation.query.filter_by(name=target).first()

    user_name = session['name']
    images = VacationPhoto.query.filter_by(vacation_id=vacation_info.id).all()

    if vacation_info.user_id == User.query.filter_by(name=session['name']).first().id:
        if request.method == 'POST':
            # Delete the selected images
            for img_name in request.form.getlist('deleted'):
                if img_name.startswith('delete'):
                    img_name = img_name.replace('\\', '')
                    img_name = img_name.split('_')[1]
                    delete_from_s3(app.config['IMAGES_BUCKET_NAME'],
                                   'static\\image\\' + session['name'] + '\\' + vacation_info.name + '\\' + img_name)
                    VacationPhoto.query.filter_by(photo_name=img_name).delete()
                    db.session.commit()

            # Upload the new images
            if _is_image():
                normalized_image_names = []
                uploaded_images = request.files.getlist('photo')
                for image in uploaded_images:
                    image_size = 'large'
                    processed_image_name, large_image, directory = _img_preparation(image_size, image,
                                                                                    vacation_info.name)
                    upload_to_s3(str(directory), large_image, app.config['IMAGES_BUCKET_NAME'])
                    normalized_image_names.append(processed_image_name)

                if _is_image():
                    _save_photos(target, normalized_image_names)
                    print('Adding image names to the DB ... Done !!')

            # Update the new description
            if vacation_info.description != request.form['description']:
                vacation_info.description = request.form['description']
                db.session.commit()

            # Update Location
            if vacation_info.location != request.form['location']:
                vacation_info.location = request.form['location']
                db.session.commit()

            # Update with_who
            if vacation_info.with_who != request.form['with_who']:
                vacation_info.with_who = request.form['with_who']
                db.session.commit()

            flash('Update was Successful !!')
            print('Update was Successful !!')
            return redirect(url_for('myVacation.edit', next=Qparam))
    else:
        flash('Username Didn\'t Match !!!')
        return redirect(url_for('myVacation.vacation', vacation_name=target))
    return render_template('edit_slideshow.html',
                           image_list=images,
                           user_name=user_name,
                           vacation_info=vacation_info,
                           form=form
                           )


@myVacation_blueprint.route('/myVacation/loggedVacations', methods=['GET', 'POST'])
@login_required
def logged_vacations():
    is_more = True
    list_of_vacation = []
    user_info = User.query.filter_by(name=session['name']).first()
    vacation = Vacation.query.filter_by(user_id=user_info.id)
    last_item = vacation[-1]
    vacation_info = vacation.limit(5).all()
    last_selected = vacation_info[-1]

    if last_item == last_selected:
        is_more = False

    for vac in vacation_info:
        vacation_img = VacationPhoto.query.filter_by(vacation_id=vac.id).first()
        list_of_vacation.append([vac.name,
                                 vac.description,
                                 vacation_img.photo_name,
                                 is_more]
                                )

    return render_template('loggedVacations.html',
                           list_of_vacation=list_of_vacation,
                           user_name=session['name']
                           )

project/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Vacation Diary {% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{{ url_for('static', filename='image/favicon.ico') }}">
    <!-- STYLES -->
    {#    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet">#}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap/css/bootstrap.css') }}">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href='//fonts.googleapis.com/css?family=Cherry Cream Soda|Shanti|PT Sans Caption' rel='stylesheet'>
    {% block link %}{% endblock %}

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
    {% block script %}{% endblock %}
</head>
<body>
{% block side_bar %}
    {% include 'includes/_side_bar.html' %}
{% endblock %}

{% block main_img %}{% endblock %}
<div id="section-1"></div>

<span class="nav-menu-link" style="font-size:30px;cursor:pointer" onclick="openNav()">&#9776;</span>
<section>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                {% block content %}{% endblock %}
            </div>
        </div>
    </div>
</section>
<section>
{% include 'recent_posts.html' %}
</section>

<footer>
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <p>Copyright &copy; VacationDiary 2017</p>
            </div>
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container -->
</footer>
<script src="https://code.jquery.com/jquery-1.12.3.min.js"></script>
<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script>
    function openNav() {
        $("#sidebar-wrapper").width("100%");
    }

    function closeNav() {
        $("#sidebar-wrapper").width(0);
    }
</script>
{% block endScript %}{% endblock %}
</body>
</html>

project/templates/comments.html
<div class="log_comments_wrapper">
    <form method="POST" action="{{ url_for('comments.log_comment', vacation_id=vacation_id, next=request.script_root + request.path) }}">
        <br>
        <h4>Leave a Comment...</h4>
        <textarea class="comments" rows="5" name="comment" placeholder="Comments..."></textarea>
        <span><input class="textareaCounter">  Characters Remaining</span>
        <br>
        <span class="comment_notification"></span><button class="submit_comment" type="Submit">Submit</button>
    </form>
</div>
<br>

project/templates/edit_slideshow.html
{% extends '_base.html' %}
{% block title %}| Edit {% endblock %}

{% set img_src = 'https://s3.amazonaws.com/vacationimages/static/image' %}
{% set deleted = [] %}
{% block content %}
    <h2><a class="vac_name" href="/myVacation/{{ vacation_info.name }}">{{ vacation_info.name }}</a></h2>
    <form class="edit_vacation" enctype=multipart/form-data role="form"
          action="/edit?next={{ request.args.get('next') }}" method="post" name="edit_form">
        <fieldset>
            {% for image in image_list %}
                <div class="image_wrapper">
                    <img class="img_edit img_edit_{{ image }}" id="{{ image }}"
                         src="{{ img_src }}/{{ user_name }}/{{ vacation_info.name }}/{{ image }}">
                    <label class="delete_img {{ image }}">X</label>
                    <input data-tag-image="0" style="display: none;" class="checkbox_{{ image }}" name="deleted" value="{{ image }}">
                </div>
            {% endfor %}
        </fieldset>
        <fieldset>
            <div class="add_img" style="clear:both">
                <label for="img_files">Want to add more images?</label>
                {{ form.photo(multiple="multiple") }}
            </div>
        </fieldset>
        <br>
        <fieldset>
            <div class="edit_desc">
                <textarea name="description">{{ vacation_info.description }}</textarea>
            </div>
        </fieldset>
        <table>
            <tr>
                <fieldset>
                    <td><label>Location</label></td>
                    <td name="location">{{ form.location }}</td>
                </fieldset>
            </tr>
            <tr>
                <fieldset>
                    <td><label>Who was with you?</label></td>
                    <td name="with_who">{{ form.with_who }}</td>
                </fieldset>
            </tr>

        </table>
        <br>
        <fieldset style="float: left;">
            <button class="btn btn-sm btn-success submit_edit" type="submit">Update</button>
        </fieldset>
    </form>
    <form action="{{ request.args.get('next') }}">
        <fieldset>
            <button class="btn btn-cancel btn-sm btn-warning" type="submit">Cancel</button>
        </fieldset>
    </form>

{% endblock %}
{##}
{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/edit_slideshow.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}
{% block endScript %}
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC9v2D3W59ZapYegAsOvu50r_mwPyM5we8&libraries=places" type="text/javascript"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.geocomplete.min.js') }}"></script>
{% endblock %}

project/templates/index.html
{% extends '_base.html' %}
{% block title %}{% endblock %}

{% block main_img %}
    {% include 'includes/_main_img.html' %}
{% endblock %}


{% block content %}
    <div class="main__header" id="main__header">
        <h3 class="main__headerTitle">Welcome to Vacation Diary</h3>
        <h5 class="main__logan">Where Everyone Shares Their Dream Vacation !!</h5>
    </div>
    <div id="main">
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec mollis justo. Orci varius natoque penatibus
            et magnis dis parturient montes, nascetur ridiculus mus. Aliquam et iaculis tortor. Duis sapien felis,
            rutrum efficitur auctor in, molestie et sapien. Phasellus vel eleifend eros. Ut vitae venenatis lacus.
            Aenean iaculis gravida dolor sit amet tincidunt. Curabitur pellentesque nulla id bibendum egestas.
            Suspendisse potenti. Suspendisse in aliquam mi, vel maximus elit. Morbi volutpat vel eros a blandit. Mauris
            mollis magna ac sagittis cursus. Orci varius natoque penatibus et magnis dis parturient montes, nascetur
            ridiculus mus. In hac habitasse platea dictumst.</p>

        <p>Cras massa eros, porttitor a semper ac, interdum eu nisi. Sed eu interdum magna, id viverra ante. Sed nec
            mattis ante, vel sagittis nisl. Aliquam ac justo cursus, euismod elit in, sodales ipsum. Praesent mattis
            rutrum sagittis. Donec hendrerit, orci eu sagittis vulputate, lorem orci efficitur felis, rhoncus rutrum
            arcu ante quis lorem. In hac habitasse platea dictumst. Aenean sed velit id ante efficitur euismod. Quisque
            mollis, purus a elementum vestibulum, nulla lacus vulputate felis, eget interdum diam nisi a eros.
            Suspendisse scelerisque sem suscipit risus auctor suscipit.</p>

        <p>In bibendum quis nibh ac pharetra. Curabitur non enim porttitor, vehicula lorem sit amet, elementum orci.
            Etiam bibendum vulputate erat, ac vulputate sapien venenatis at. In hac habitasse platea dictumst. Cras
            condimentum eleifend cursus. Aenean mattis lorem in urna tristique porttitor. Suspendisse ut metus a nulla
            facilisis rutrum. Duis gravida placerat ex, non consequat mi bibendum nec. Vivamus accumsan gravida ex, ut
            dapibus mauris sollicitudin a. Aliquam odio tortor, ornare eget fringilla in, vestibulum sit amet justo.</p>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

project/templates/logVacation.html
{% extends '_base.html' %}
{% block title %}| Log Vacation{% endblock %}

{% block content %}
    <script>
        $(function () {
            $('.switchWrapper').append('<p>Private</p>');
        });
        function switchButton() {
            if ($('.checkbox').is(':checked')) {
                $('.switchWrapper p').remove();
                $('.switchWrapper').append('<p>Public</p>');
            } else {
                $('.switchWrapper p').remove();
                $('.switchWrapper').append('<p>Private</p>');
            }
        }
    </script>
    <h3>Save Your Vacation</h3>
    &nbsp;
    <form class="logVacation" enctype=multipart/form-data role="form" method="post" action="/myVacation/logVacation">
        <div class="switchWrapper">
            <small>How would you like this vacation to be saved?</small><br>
            <label class="switch" onclick="switchButton()">
                <input class="checkbox" type="checkbox" name="public">
                <div class="slider round"></div>
            </label>
        </div>
        {{ form.csrf_token }}

        <br>
        {{ form.vacation_name(placeholder="Name Your Vacation") }}
        <p><span class="error">
            {% if form.vacation_name.errors %}
                {% for error in form.vacation_name.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </span></p>
        <br>
        <fieldset>
            <td name="location">{{ form.location(placeholder="Where was it?") }}</td>
        </fieldset>
        <p><span class="error">
            {% if form.location.errors %}
                {% for error in form.location.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </span></p>
        <br>
        {{ form.with_who(placeholder='Who was with you') }}
        <br>
        <br>
        {{ form.description(placeholder="Tell us about your vacation... or not.") }}<br>
        {{ form.when(class="datepicker", placeholder="when?") }}
        <p><span class="error">
            {% if form.when.errors %}
                {% for error in form.when.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </span></p>
        <br><br>
        <h6>Upload your vacation Pictures</h6>
        {{ form.photo(multiple="multiple", class_="text-center center-block well well-sm") }}
        <p><span class="error">
            {% if form.photo.errors %}
                {% for error in form.photo.errors %}
                    {{ error }}
                {% endfor %}
            {% endif %}
        </span></p>
        <br>

        <button class="btn btn-primary" value="upload" type="submit">Save Vacation</button>
        <span></span>
        <button class="btn btn-default" value="Cancel" type="reset">Cancel</button>
    </form>
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

{% block endScript %}
    <script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyC9v2D3W59ZapYegAsOvu50r_mwPyM5we8&libraries=places" type="text/javascript"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery.geocomplete.min.js') }}"></script>
{% endblock %}

{% block link %}{% endblock %}

project/templates/loggedVacations.html
{% extends '_base.html' %}
{% block title %}{% endblock %}

{% block content %}
    {% set img_src = 'https://s3.amazonaws.com/vacationimages/static/image/' %}
    <div id="List_of_all_vacations_wrapper">
        {% if list_of_vacation|length > 0 %}
            <h3 class="vacation_list__h3">LIST OF MY VACATIONS</h3>
            {% for i in list_of_vacation %}
                <div class="logged_vacation_container">
                    <a class="vac_name" href="/myVacation/{{ i[0] }}"> {{ i[0] }}</a>
                    <a class="vac_list_img" href="/myVacation/{{ i[0] }}"><img class="vacation_list_img" src="
                            {{ img_src }}{{ user_name }}/{{ i[0] }}/{{ i[2] }}"></a>
                    <p class="vacation_list_desc">{{ i[1] }}</p>
                    <hr class="between_logged_vacations">
                </div>
                {% set is_more = i[4] %}
            {% endfor %}
            {% if is_more %}
                <button id="load_more">Load More</button>
            {% endif %}
        {% else %}
            <p>You have no logged vacations. Would you like to share with us?</p>
            <form action="/myVacation/logVacation">
                <input type="submit" class="log_vacation" value="Log Vacation">
            </form>
        {% endif %}
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/listOfVacations.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

project/templates/login.html
{% extends "_base.html" %}
{% block title %}| Login{% endblock %}


{% block content %}

    <div id="pop-up-modal" class="pop-up-modal">
        <!-- Modal content -->
        <div class="pop-up-modal-content">
            <div class="pop-up-modal-header">
                <span class="pop-up-close">&times;</span>
                <h3>Please sign-in</h3>
            </div>
            <div class="pop-up-modal-body">
                <form class="form-signin" role="form" method="post" action="/login">
                    {{ form.csrf_token }}
                    <p>{{ form.name(placeholder="user name") }}</p>
                    <p>
                        <span class="error">
                            {% if form.name.errors %}
                                {% for error in form.name.errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                        </span>
                    </p>
                    <p>{{ form.password(placeholder="password") }}</p>
                    <p>
                        <span class="error">
                            {% if form.password.errors %}
                                {% for error in form.password.errors %}
                                    {{ error }}
                                {% endfor %}
                            {% endif %}
                        </span>
                    </p>
                    <button class="btn btn-sm btn-success" type="submit">Sign in</button>
                    <br>
                    <br>
                    <p><em>Need an Account?</em><a href="/register"> Signup</a></p>
                </form>
            </div>
            <div class="pop-up-modal-footer">
                <h3>Modal Footer</h3>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/signIn.js') }}"></script>

{% endblock %}

project/templates/myVacation.html
{% extends '_base.html' %}
{% block title %}My Vacation {% endblock %}

{% block main_img %}
    {% include 'includes/_main_img.html' %}
{% endblock %}

{% block content %}
    <div class="vacation-wrapper">
        <h4>Welcome to your vacation page nonsense.</h4>
        <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit.
            Cras ac lectus quis ante posuere convallis.
            Mauris sit amet metus non metus congue porta.
            Nulla vel ex mollis, consectetur leo quis, aliquet diam.
            Cras eget ligula nec turpis feugiat ullamcorper ac eget nunc.
            Sed accumsan dui in fermentum scelerisque.
            Vivamus auctor turpis sed nisi suscipit ullamcorper.
            Integer vel sem condimentum, porttitor libero vitae, commodo odio.
            Aenean maximus orci ac ex molestie ultricies.
            Aenean ac sem in ante posuere egestas.
            Mauris dapibus est sed enim finibus, sit amet dignissim nunc dignissim.
            Integer elementum massa eget consequat rutrum.
            Vestibulum elementum lectus et convallis posuere.
            Aenean ultricies justo sollicitudin facilisis consectetur.
            Fusce a lorem quis augue ultrices semper vitae sed libero.
            Vivamus aliquet lectus et metus blandit porttitor.
            Quisque interdum arcu sed eros tempor vestibulum.
            Donec eu elit efficitur, consectetur urna ac, interdum nunc.
            Mauris eu leo quis dui auctor lacinia vitae vel justo.
            Suspendisse in tortor ac tellus ullamcorper laoreet in sed odio.
            Proin ac sem in magna dignissim faucibus.
            Phasellus ut erat imperdiet mi luctus sodales at et turpis.
            Curabitur nec odio at nunc accumsan vulputate.
        </p>
    </div>
{% endblock %}

{% block script %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/main.js') }}"></script>
{% endblock %}

project/templates/recent_posts.html
{% set data  =  recent_posts() %}
{% set img_src = 'https://s3.amazonaws.com/vacationimages/static/image/' %}
{% if data %}
    <div class="container">
        <!-- Page Heading -->
        <hr>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="recent_posts_header">Recent Posts
                </h1>
            </div>
        </div>
        <!-- /.row -->
        {% for i in data %}
            <div class="row recent_posts_row">
                <div class="col-md-7 recent_post_left">
                    <a href="/myVacation/{{ i['name_slugged'] }}">
                        <img class="img-responsive"
                             src="{{ img_src }}{{ i['user_name'] }}/{{ i['name_slugged'] }}/{{ i['main_image'] }}"
                             alt="{{ i['name_slugged'] }}_image">
                    </a>
                </div>
                <div class="col-md-5 recent_post_right">
                    <h3 class="recent_posts__h3">{{ i['name_original'] }}</h3>
                    {#                <h4>Subheading</h4>#}
                    <p class="vacation_desc">{{ i['description'] }}</p>
                    <a class="btn btn-primary" href="/myVacation/{{ i['name_slugged'] }}" class="vacation_name">View
                        Vacation <span class="glyphicon glyphicon-chevron-right"></span></a>
                </div>
            </div>
            <!-- /.row -->
            <hr class="recent_posts_hr">
        {% endfor %}
    </div>

{% else %}
    <h3>No Recent Post Available</h3>
{% endif %}